project_id = "heyjvukoaxgkzbgcxakn"

[functions.generate-certificate]
verify_jwt = false

[functions.send-test-results]
verify_jwt = false

[functions.generate-result-download]
verify_jwt = false

[functions.get-test-questions]
verify_jwt = true

[functions.grade-test]
verify_jwt = true
